#!/usr/bin/env bash
sudo chmod -R u+x ./*

docker image pull rafaelcgstz/magento2

sed -i '' -e "s/<project_name>/$1/g" docker-compose.yml;

if [ ! -e src/index.php ]; then
  echo "<?php phpinfo();" > src/index.php;
fi

if [ -d src/app/etc ]; then  
  if [ ! -e src/app/etc/env.php ]; then
    cp .docker/users/env.sample.php src/app/etc/env.php;
  fi
fi

chmod -R 777 src

bash start
