#!/usr/bin/env bash
docker-compose up -d && \
version=$(git describe --tags $(git rev-list --tags --max-count=1))
echo "
===================== 🚀 Done 🚀 ===================

      v.$version
      Access your new links:

      🌎 Web server: http://magento2.test/
      🌎 Admin panel: http://magento2.test/manager, User: admin, Password: a123456
      ⚙️ PHPMyAdmin: http://localhost:8080
      ✉️ Local emails: http://localhost:8025

===================== 🚀 Done 🚀 ==================="
